fixed case when request does not contain Perun data
CESNET/einfra-aai-proxy-idp-template pull request #13
Opened 2019-01-02 10:31 UTC by Gaeldrin

Fix for corner case when the request comes without information from Perun.
This happens when user comes from Perun SP.

Added detection of this state and disabled writing information to Perun
as there would be no place to write it to.

Signed-off-by: Petr Vsetecka <vsetecka@cesnet.cz>

2019-01-02 10:32 UTC, Gaeldrin commented
@pajavyskocil

2019-01-24 12:21 UTC, pajavyskocil commented on CHANGELOG.md
> +## [v1.3.1]
Please remove version.

2019-01-24 12:22 UTC, vyskocilpavel requested changes
Please remove version in changelog and rebase your code

2019-02-04 08:41 UTC, Gaeldrin commented on CHANGELOG.md
> +## [v1.3.1]
removed by rebasing

2019-02-08 07:54 UTC, vyskocilpavel approved these changes

2019-02-20 07:48 UTC, merged