Security improvement - scripts calling
CESNET/einfra-aai-proxy-idp-template pull request #34
Opened 2021-03-08 12:39 UTC by BaranekD

This PR is dependent on https://github.com/CESNET/perun-simplesamlphp-module/pull/139 - The code in this PR cannot work without the script for the hashes generating.

2021-03-19 16:06 UTC, dBucik requested changes
Some small changes, otherwise OK.

2021-03-19 16:06 UTC, dBucik commented on lib/Auth/Process/IsCesnetEligible.php
> +        $this->pathToKey = $config['pathToKey'];
Please use the defined constant (_self::PATH_TO_KEY_) instead.

2021-03-19 16:06 UTC, dBucik commented on lib/Auth/Process/IsCesnetEligible.php
> +                $challenge = curl_exec($curlChallenge);
I don't see any call to close the curl. (`curl_close($ch);`)

Also, what if the curl has failed?
```
if (curl_errno($ch)) {
    $error_msg = curl_error($ch);
}
```

2021-03-19 16:06 UTC, dBucik commented on lib/Auth/Process/IsCesnetEligible.php
> +                        ->addSignature($jwk, ['alg' => 'RS512'])
perhaps introduce a constant for the ALG value that can be used across the classes to prevent changing it in some place and forgetting about the secondary places.

2021-03-19 16:06 UTC, dBucik commented on www/updateIsCesnetEligible.php
> +    $headerCheckerManager = new HeaderCheckerManager([new AlgorithmChecker(['RS512'])], [new JWSTokenSupport()]);
Perhaps use a constant as mentioned above.

2021-03-19 16:06 UTC, dBucik commented on www/updateIsCesnetEligible.php
> +    $cesnetEligibleLastSeenAttrName = $claims['data']['cesnetEligibleLastSeenAttrName'];
Use constants for the array keys.

2021-06-18 07:05 UTC, vyskocilpavel approved these changes

2021-06-18 07:21 UTC, merged